version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      astro:
        patterns: ['astro', '@astrojs/*']
      tailwind:
        patterns: ['tailwindcss', '@tailwindcss/*', 'prettier-plugin-tailwindcss']
      lint-and-test:
        patterns:
          [
            'eslint*',
            'typescript-eslint',
            '@typescript-eslint/*',
            'prettier*',
            '@playwright/*',
            '@axe-core/*',
          ]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
